// Code generated by genkeys.go; DO NOT EDIT.

package key

const (
	Null       rune = 0
	CtrlA      rune = 1
	CtrlB      rune = 2
	CtrlC      rune = 3
	CtrlD      rune = 4
	CtrlE      rune = 5
	CtrlF      rune = 6
	CtrlG      rune = 7
	CtrlH      rune = 8
	CtrlI      rune = 9
	CtrlJ      rune = 10
	CtrlK      rune = 11
	CtrlL      rune = 12
	Enter      rune = 13
	CtrlM      rune = 13
	CtrlN      rune = 14
	CtrlO      rune = 15
	CtrlP      rune = 16
	CtrlQ      rune = 17
	CtrlR      rune = 18
	CtrlS      rune = 19
	CtrlT      rune = 20
	CtrlU      rune = 21
	CtrlV      rune = 22
	CtrlW      rune = 23
	CtrlX      rune = 24
	CtrlY      rune = 25
	CtrlZ      rune = 26
	Esc        rune = 27
	Del        rune = 127
	ArrowUp    rune = 1792833
	ArrowDown  rune = 1792834
	ArrowRight rune = 1792835
	ArrowLeft  rune = 1792836
)
